config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "shops/search" => "shops#search"

  get "shops/tagsearch" => "shops#tagsearch"

  get "shops/mapsearch" => "shops#mapsearch"

  get "shops/condition" => "shops#condisearch"

  get "shops/random" => "shops#randomsearch"

  get "shops/index2" => "shops#index2"

  get "shops/index3" => "shops#index3"

  get "shops/index4" => "shops#index4"

  get "shops/about" => "shops#about"

  get "top2" => "shops#top2"

  get "top" => "shops#top"

  resources :shops do
    resources :likes, only: [:create, :destroy]
  end

  resources :genres

  resources :infos

  resources :prices

  root 'shops#top'
end

app/models/shop.rb
class Shop < ApplicationRecord
    belongs_to :user
    belongs_to :genre
    belongs_to :price

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    mount_uploader :image, ImageUploader

    geocoded_by :address
    after_validation :geocode, if: :address_changed?
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    def top
        @shop_ranks = Shop.find(Like.group(:shop_id).order('count(shop_id) desc').limit(3).pluck(:shop_id))
        @infos = Info.order(created_at: :desc).limit(3)
        @genres = Genre.all
        @prices = Price.all
    end
    def top2
        @shop_ranks = Shop.find(Like.group(:shop_id).order('count(shop_id) desc').limit(3).pluck(:shop_id))
        @infos = Info.order(created_at: :desc).limit(3)
        @genres = Genre.all
        @prices = Price.all
    end
    def search 
    end
    def tagsearch
    end
    def condisearch
        @genres = Genre.all
        @shops = Shop.all
    end
    def mapsearch
        @shops = Shop.all
        gon.shops = Shop.all
        @genres = Genre.all
    end
    def randomsearch
    end
    def about
    end
    def index
        @genres = Genre.all
        @prices = Price.all
        if params[:search] == nil
            if params[:search2] == nil
                @shops = Shop.all
            else if params[:search2] == ''
                @shops = Shop.all
              else
                @shops = Shop.where("address LIKE ? ",'%' + params[:search2] + '%')
              end 
            end
          elsif params[:search] == ''
            if params[:search2] == nil
                @shops = Shop.all
            else if params[:search2] == ''
                @shops = Shop.all
              else
                @shops = Shop.where("address LIKE ? ",'%' + params[:search2] + '%')
              end 
            end
          else
            if params[:search2] == nil
                @shops = Shop.where("name LIKE ? ",'%' + params[:search] + '%')
            else if params[:search2] == ''
                @shops = Shop.where("name LIKE ? ",'%' + params[:search] + '%')
            else
                @shops = Shop.where("name LIKE ? ",'%' + params[:search] + '%').where("address LIKE ? ",'%' + params[:search2] + '%')
            end 
            end
          end 
        end
    def index2
        if params[:genre_id] != nil
            @shops = Shop.where(genre_id: params[:genre_id])
        else
            @shops = Shop.where(price_id: params[:price_id])
        end
        @genres = Genre.all
        @prices = Price.all
    end
    def index3
        @shops = Shop.order("RAND()").limit(params[:num])
        @genres = Genre.all
        @prices = Price.all
    end
    def index4
        @shops = Shop.where("name LIKE ? ",'%' + params[:search] + '%').or(Shop.where("address LIKE ? ",'%' + params[:search] + '%'))
        @genres = Genre.all
        @prices = Price.all
    end
    def new
        @shop = Shop.new
        @genre = Genre.new
        @genres = Genre.all
        @prices = Price.all
    end
    def create
        @shop = Shop.new(shop_params)
        @shop.user_id = current_user.id
        if @shop.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end
    def show
        @shop = Shop.find(params[:id])
        @like = Like.new
        @genres = Genre.all
        @prices = Price.all
    end
    def edit
        @shop = Shop.find(params[:id])
    end
    def update
        @shop = Shop.find(params[:id])
        if @shop.update(shop_params)
          redirect_to :action => "show", :id => @shop.id
        else
          redirect_to :action => "new"
        end
    end
    def destroy
        Shop.find(params[:id]).destroy
        redirect_to action: :index
    end

    private
    def shop_params
        params.require(:shop).permit(:name, :phone, :address, :rank, :intro, :atmos, :image, :latitude, :longitude, :genre_id, :price_id)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/edit.html.erb
<h1>編集ページ</h1>

<%= form_for @shop do |f| %>
    <div class="field">
    <p>店名：<%= f.text_field :name %></p>
    <p>電話番号：<%= f.text_field :phone %></p>
    <p>住所：<%= f.text_field :address %></p>
    <p>店の紹介文：<%= f.text_area :intro, :size => "50x10" %></p>
    <p>雰囲気：<%= f.text_field :atmos %></p>
    <p>１人で行きやすい度：<%= f.number_field :rank, min: 1, max: 3 %></p>
    <p>店の画像：<%= f.label :image %>
    <%= f.file_field :image %></p>
    <p>ジャンルID：<%= f.number_field :genre_id %></p>
    <p>価格帯：<%= f.text_field :price %></p>
    <%= f.submit "編集する" %>
    </div>
<% end %>

<footer>
<p>Copyright © YuseiDoi All Rights Reserved.</p>
</footer>


app/views/shops/index.html.erb
<%= stylesheet_link_tag 'shops', :media => "all" %>

<div class="under-header-container">
<div class="under-header3">
<%# app/assets/images %>
<%= image_tag "icon.png", { alt: "Rails icon", id: "assets", class: "image", width: "35px", height: "35px" } %>
</div>
<div class="under-header">
<p>ヒトリエ</p>
</div>
<div class="under-header2">
<div class="under-header-section">
<%= link_to "about", shops_about_path %>
</div>

<% if user_signed_in? %>

<div class="under-header-section">
<%= link_to "mypage", user_path(current_user.id) %>
</div>
<div class="under-header-section">
<%= link_to 'log out', destroy_user_session_path, method: :delete %>
</div>
<div class="under-header-section">
<%= link_to "top", top2_path %>
</div>
<div class="under-header-section">
<ul id="menu">
    <li><a href="">search</a>
        <ul class="child_menu">
            <li><%= link_to "キーワード検索する", shops_search_path, class: 'btn btn-default' %></li>
            <li><%= link_to "地図から検索する", shops_mapsearch_path, class: 'btn btn-default' %></li>
            <li><%= link_to "条件検索する", shops_condition_path, class: 'btn btn-default' %></li>
            <li><%= link_to "優柔不断なあなたに", shops_random_path, class: 'btn btn-default' %></li>
        </ul>
    </li>
</ul>
</div>
<div class="under-header-section">
<%= form_tag({controller:"shops",action:"index4"}, method: :get, class: "btn") do %>
    <%= text_field_tag :search %>
    <input type="submit" value"Let's Go" class="button2">
    <% end %>
 </div>

<% else %>

<div class="under-header-section">
<%= link_to "sign in", new_user_registration_path %>
</div>
<div class="under-header-section">
<%= link_to "top", top_path %>
</div>
<div class="under-header-section">
<ul id="menu">
    <li><a href="">search</a>
        <ul class="child_menu">
            <li><%= link_to "キーワード検索する", shops_search_path, class: 'btn btn-default' %></li>
            <li><%= link_to "地図から検索する", shops_mapsearch_path, class: 'btn btn-default' %></li>
            <li><%= link_to "条件検索する", shops_condition_path, class: 'btn btn-default' %></li>
            <li><%= link_to "優柔不断なあなたに", shops_random_path, class: 'btn btn-default' %></li>
        </ul>
    </li>
</ul>
</div>
<div class="under-header-section">
<%= form_tag({controller:"shops",action:"index4"}, method: :get, class: "btn") do %>
    <%= text_field_tag :search %>
    <input type="submit" value"Let's Go" class="button2">
    <% end %>
 </div>

<% end %>

</div>
</div>

<div class="above-shop-container">
<h3>検索結果</h3>
</div>

<div class="shop-container">
    <% @shops.each do |t| %>
        <div class="shop">
        <div class="img-box">
        <%= image_tag t.image_url, size: "100%×100%" if t.image? %>
        </div>

        <div class="shop-explain-box">
            <div class="top3-shop-explain">
            <h3><%= t.name %><br>
            <p>ジャンル：<%= @genres[(t.genre_id - 1)]['name'] %>　<%= @prices[(t.price_id - 1)]['pricerange'] %>
            </h3>
            </p>
            </div>
        
            <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
　 　　         <%=link_to shop_like_path(id: t.id, shop_id: t.id), method: :delete do%>
    　      <div class="LikesIcon">
                <i class="far fa-heart LikesIcon-fa-heart"></i>
                <%=t.likes.count%>
                <div class="top3-shop-method">
                <% if current_user.id == 3 %>  
                    <%= link_to "削除する", shop_path(t.id), method: :delete %>
                <% end %>
                <%= link_to "詳しく見る", shop_path(t.id) %>
                </div>    
            </div>
　　　      <%end%>
            <% else %>
                <%=link_to shop_likes_path(id: t.id, shop_id: t.id), method: :post do%>
            <div class="LikesIcon">
                <i class="far fa-heart LikesIcon-fa-heart"></i>
                <%=t.likes.count%>
                <div class="top3-shop-method">
                <%= link_to "詳しく見る", shop_path(t.id) %>
                </div>    
            </div>
　　        <%end%>
            <% end %>
            <% end %>
        </div>
        </div>
    <% end %>
</div>

<script src="https://embed.small.chat/T01DG63L5GSG01D1DTHFTR.js" async></script>

<div class="above-footer">
</div>

<script>
$(function(){
    $("ul#menu li").hover(function(){
        $("> ul:not(:animated)" , this).animate({
            height : "toggle",
            opacity : "toggle"
        }, 500 );
    },
    function(){
        $("> ul" , this).fadeOut("slow");
    });
});
</script>

<script>
$('.LikesIcon').on('click', function() {
  let $btn = $(this);
  // Likeボタンがonクラス持っていたら
  if ($btn.hasClass('on')) {

    $btn.removeClass('on');

    // 白抜きアイコンに戻す
    $btn.children("i").attr('class', 'far fa-heart LikesIcon-fa-heart');

  } else {

    $btn.addClass('on');

    // ポイントは2つ！！
    // ①アイコンを変更する
    // far fa-heart（白抜きアイコン）
    // ⇒ fas fa-heart（背景色つきアイコン）
    // ②アニメーション+アイコン色変更用のheartクラスを付与する

    $btn.children("i").attr('class', 'fas fa-heart LikesIcon-fa-heart heart');

  }
}</script>

app/views/shops/mapsearch.html.erb
<%= stylesheet_link_tag 'shops', :media => "all" %>

<div class="under-header-container">
<div class="under-header3">
<%# app/assets/images %>
<%= image_tag "icon.png", { alt: "Rails icon", id: "assets", class: "image", width: "35px", height: "35px" } %>
</div>
<div class="under-header">
<p>ヒトリエ</p>
</div>
<div class="under-header2">
<div class="under-header-section">
<%= link_to "about", shops_about_path %>
</div>

<% if user_signed_in? %>

<div class="under-header-section">
<%= link_to "mypage", user_path(current_user.id) %>
</div>
<div class="under-header-section">
<%= link_to 'log out', destroy_user_session_path, method: :delete %>
</div>
<div class="under-header-section">
<%= link_to "top", top2_path %>
</div>

<% else %>

<div class="under-header-section">
<%= link_to "sign in", new_user_registration_path %>
</div>
<div class="under-header-section">
<%= link_to "top", top_path %>
</div>

<% end %>

</div>
</div>

<div class="tabs-container">
<input id="all" type="radio" name="tab_item" checked>
<label class="tab_item" for="all"><%= link_to "キーワード検索", shops_search_path %>
</label>
<input id="programming" type="radio" name="tab_item">
<label class="tab_item_2" for="programming"><%= link_to "地図から検索", shops_mapsearch_path %>
</label>
<input id="design" type="radio" name="tab_item">
<label class="tab_item" for="design"><%= link_to "条件検索", shops_condition_path %>
</label>
<input id="all" type="radio" name="tab_item" checked>
<label class="tab_item" for="all"><%= link_to "ランダム検索", shops_random_path %>
</label>
</div>


<div class="search-boxes-container2">

<div class="search-left-box2">
</div>

<div class="search-center-box2">

<div id='map'></div>

<style>
#map{
    height: 600px;
    width: 1200px;
    margin-top: 20px;
    margin-left: 5%;

    a {
        color: #FB7D79;
        text-decoration: none;
      }  
}
</style>


<script src="https://embed.small.chat/T01DG63L5GSG01D1DTHFTR.js" async></script>


<script>

let map
let geocoder
let marker = []; 
let infoWindow = []; 
const shops = gon.shops; 


function initMap(){
    geocoder = new google.maps.Geocoder()
    map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.6809591, lng: 139.7673068},
    zoom: 13
    });
    for (let i = 0; i < shops.length; i++) {
        geocoder.geocode( { 'address': shops[i].address }, function(results, status) {
        if (status == 'OK') {
            map.setCenter(results[0].geometry.location);
            marker[i] = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });
            let id = shops[i]['id']
            infoWindow[i] = new google.maps.InfoWindow({
            content: `<a href='/shops/${id}'>${shops[i].name}</a>`
            });
            marker[i].addListener("click", function(){
                infoWindow[i].open(map, marker[i]);
            });
        } else {
            alert('Geocode was not successful for the following reason: ' + status);
        }
        });
    }



}
function codeAddress(){
    // 入力を取得
    let inputAddress = document.getElementById('address').value;
    // geocodingしたあとmapを移動
}

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5Hjy8PYIQ010xXxQer6gvZb52Vm0_xWw&callback=initMap" async defer></script>
</div>

<div class="search-right-box2">
</div>

</div>

<script src="https://embed.small.chat/T01DG63L5GSG01D1DTHFTR.js" async></script>

<div class="above-footer">
</div>

app/views/shops/show.html.erb
<%= stylesheet_link_tag 'shops', :media => "all" %>

<div class="under-header-container"  data-animsition-in-class="fade-in">
<div class="under-header3">
<%# app/assets/images %>
<%= image_tag "icon.png", { alt: "Rails icon", id: "assets", class: "image", width: "40px", height: "40px" } %>
</div>
<div class="under-header">
<p>ヒトリエ</p>
</div>
<div class="under-header2">
<div class="under-header-section">
<%= link_to "about", shops_about_path %>
</div>
<div class="under-header-section">
<%= link_to "mypage", user_path(current_user.id) %>
</div>
<div class="under-header-section">
<%= link_to 'log out', destroy_user_session_path, method: :delete %>
</div>
<div class="under-header-section">
<ul id="menu">
    <li><a href="">search</a>
        <ul class="child_menu">
            <li><%= link_to "キーワード検索する", shops_search_path, class: 'btn btn-default' %></li>
            <li><%= link_to "地図から検索する", shops_mapsearch_path, class: 'btn btn-default' %></li>
            <li><%= link_to "条件検索する", shops_condition_path, class: 'btn btn-default' %></li>
            <li><%= link_to "優柔不断なあなたに", shops_random_path, class: 'btn btn-default' %></li>
        </ul>
    </li>
</ul>
</div>
<div class="under-header-section">
<% if user_signed_in? %>
<%= link_to "top", top2_path %>
<% else %>
<%= link_to "top", top_path %>
<% end %>
 </div>
 </div>
</div>

<div class="shop-show-container">
<div class="shop-show-img-box">
<%= image_tag @shop.image_url, size: "100%×100%" if @shop.image? %>
</div>
<div class="show-shop">
    <div class="shop-name">
    <h2><%= @shop.name %></h2>
    </div>
    <p>住所：<%= @shop.address %></p>
    <p>電話番号：<%= @shop.phone %></p>
    <p>１人での行きやすさ：<%= @shop.rank %></p>
    <p>雰囲気：<%= @shop.atmos %></p>
    <p>ジャンル：<%= @genres[(@shop.genre_id - 3)]['name'] %></p>
    <p>価格帯：<%= @prices[@shop.price_id]['pricerange'] %></p>
    <div class="shop-intro-box">
    <div class="grad-wrap">
    <span class="grad-trigger"></span>
    <div class="grad-item">
        <p>店の紹介：<%= @shop.intro %></p>
    </div>
    </div>
    </div>
  
    <% if user_signed_in? %>
    <p>いいね件数: <%= @shop.likes.count %></p>
      <% if current_user.already_liked?(@shop) %>
　 　   <%=link_to shop_like_path(@shop), method: :delete do%>
      <p>いいねを取り消す</p>
　　　<%end%>
      <% else %>
        <%=link_to shop_likes_path(@shop), method: :post do%>
      <p>いいね</p>
　　 <%end%>
  <% end %>
  <% end %>

  <% if user_signed_in? && current_user.id == 3 %> 
    <%= link_to "編集する", edit_shop_path(@shop.id) %>
    <%= link_to "削除する", shop_path(@shop.id), method: :delete %>
  <% end %>
</div>
</div>

</div>

<!--
<h2>いいねしたユーザー</h2>
<% @shop.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
-->

<div class="show-map-box">
<div class="show-map-explain">
<p>店の位置を確認する</p>
</div>
<div id="map"></div>

<style type="text/css">
  #map { height: 600px;
         width: 85%;
         margin-left: 7.5%;
         margin-right: 7.5%;
        }
</style>
<script>
function initMap(latlng) {
  var map = new google.maps.Map(document.getElementById('map'), {
    center: latlng,
    zoom: 16
  });

  var marker = new google.maps.Marker({
    position: latlng,
    map: map
  });
}

function getLatLng() {
  var geocoder = new google.maps.Geocoder();

  geocoder.geocode({
    address: "<%= @shop.address %>"
  }, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      for (var i in results) {
        if (results[i].geometry) {
          var latlng = results[i].geometry.location;
          initMap(latlng)
        }
      }
    }
  });
}
</script>
</div>

<script src="https://embed.small.chat/T01DG63L5GSG01D1DTHFTR.js" async></script>

<div class="above-footer">
</div>

<script>
$(function(){
    $("ul#menu li").hover(function(){
        $("> ul:not(:animated)" , this).animate({
            height : "toggle",
            opacity : "toggle"
        }, 500 );
    },
    function(){
        $("> ul" , this).fadeOut("slow");
    });
});
</script>

<script>
new jBox('Tooltip', {
  attach: '.tooltip'
});
</script>

<script>
var itemHeights = [];
var returnHeight;

$(function(){
  $(".grad-item").each(function(){ //ターゲット(縮めるアイテム)
    var thisHeight = $(this).height(); //ターゲットの高さを取得
    itemHeights.push(thisHeight); //それぞれの高さを配列に入れる
    $(this).addClass("is-hide"); //CSSで指定した高さにする
    returnHeight = $(this).height(); //is-hideの高さを取得
  });
});

$(".grad-trigger").click(function(){ //トリガーをクリックしたら
  if(!$(this).hasClass("is-show")) {
    var index = $(this).index(".grad-trigger"); //トリガーが何個目か
    var addHeight = itemHeights[index]; //個数に対応する高さを取得
    $(this).addClass("is-show").next().animate({height: addHeight},200).removeClass("is-hide"); //高さを元に戻す
  } else {
    $(this).removeClass("is-show").next().animate({height: returnHeight},200).addClass("is-hide"); //高さを制限する
  }
});
</script>

app/views/shops/top2.html.erb
<%= stylesheet_link_tag 'shops', :media => "all" %>

<div class="under-header-container"  data-animsition-in-class="fade-in">
<div class="under-header3">
<%# app/assets/images %>
<%= image_tag "icon.png", { alt: "Rails icon", id: "assets", class: "image", width: "35px", height: "35px" } %>
</div>
<div class="under-header">
<p>ヒトリエ</p>
</div>
<div class="under-header2">
<div class="under-header-section">
<%= link_to "about", shops_about_path %>
</div>
<div class="under-header-section">
<%= link_to "mypage", user_path(current_user.id) %>
</div>
<div class="under-header-section">
<%= link_to 'log out', destroy_user_session_path, method: :delete %>
</div>
<div class="under-header-section">
<ul id="menu">
    <li><a href="">search</a>
        <ul class="child_menu">
            <li><%= link_to "キーワード検索する", shops_search_path, class: 'btn btn-default' %></li>
            <li><%= link_to "地図から検索する", shops_mapsearch_path, class: 'btn btn-default' %></li>
            <li><%= link_to "条件検索する", shops_condition_path, class: 'btn btn-default' %></li>
            <li><%= link_to "優柔不断なあなたに", shops_random_path, class: 'btn btn-default' %></li>
        </ul>
    </li>
</ul>
</div>
<div class="under-header-section">
<%= form_tag({controller:"shops",action:"index4"}, method: :get) do %>
    <%= text_field_tag :search %>
    <input type="submit" value:"Let's Go" class="button2">
 <% end %>
 </div>
 </div>
</div>

<div class="a">
    <div class="b">
        <img class="c" src="assets/food8.jpg">
        <p>Enjoy your Hitori Gohan</p>
    </div>
    <div class="b">
        <img class="c" src="assets/food10.jpg">
        <p>Enjoy your Hitori Gohan</p>
    </div>
    <div class="b">
        <img class="c" src="assets/food13.jpg">
        <p>Enjoy your Hitori Gohan</p>
    </div>
</div>


<div class="animation">
<div class="anm_mod right delay">
<div class="behind-box-1">
<div class="sections">
<div class="section-word-1">
    <h3>店を探す</h3>
</div>
<div class="anm_mod right delay">
<div class="section-word-2">
    <p>4つの検索方法からあなたにぴったりのお店を探しましょう</p>
</div>
</div>
</div>

<div class="anm_mod right delay">

<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide">
        <%# app/assets/images %>
        <%= link_to image_tag("search1.jpg", { alt: "Rails icon", id: "assets", class: "image", width: "600px" }), shops_search_path %>
        <p>キーワードで検索する</p>    
        </div>
        <div class="swiper-slide">
        <%# app/assets/images %>
        <%= link_to image_tag("map1.jpg", { alt: "Rails icon", id: "assets", class: "image", width: "600px" }), shops_mapsearch_path %>   
        <p>地図で検索する</p>     
        </div>
        <div class="swiper-slide">
        <%# app/assets/images %>
        <%= link_to image_tag("search2.jpg", { alt: "Rails icon", id: "assets", class: "image", width: "600px" }), shops_condition_path %>
        <p>ジャンルで検索する</p>        
        </div>
        <div class="swiper-slide">
        <%# app/assets/images %>
        <%= link_to image_tag("search3.jpg", { alt: "Rails icon", id: "assets", class: "image", width: "600px" }), shops_random_path %>   
        <p>優柔不断なあなたへ</p>     
        </div>
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>
    
    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    </div>

</div>

<div class="anm_mod left delay">
<div class="behind-box-2">

<div class="sections">
<div class="anm_mod left delay">
<div class="section-word-3">
    <h3>いいね数Top3の店を見てみる</h3>
</div>
<div class="anm_mod left delay">
<div class="section-word-4">
    <p>みんなのお気に入りの店から今日の店を探しましょう</p>
</div>
</div>
</div>
</div>
<div class="anm_mod left delay">
<div class="shop-container">
    <% @shop_ranks.each do |t| %>
        <div class="shop">
        <div class="img-box">
        <%= image_tag t.image_url, size: "100%×100%" if t.image? %>
        </div>

        <div class="shop-explain-box">
            <div class="top3-shop-explain">
            <h3><%= t.name %><br>
            <p>ジャンル：<%= @genres[(t.genre_id - 1)]['name'] %>　<%= @prices[(t.price_id - 1)]['pricerange'] %>
            </h3>
            </p>
            </div>
        
            <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
　 　　         <%=link_to shop_like_path(id: t.id, shop_id: t.id), method: :delete do%>
    　      <div class="LikesIcon">
                <i class="far fa-heart LikesIcon-fa-heart"></i>
                <%=t.likes.count%>
                <div class="top3-shop-method">
                <%= link_to "削除する", shop_path(t.id), method: :delete %>
                <%= link_to "詳しく見る", shop_path(t.id) %>
                </div>    
            </div>
　　　      <%end%>
            <% else %>
                <%=link_to shop_likes_path(id: t.id, shop_id: t.id), method: :post do%>
            <div class="LikesIcon">
                <i class="far fa-heart LikesIcon-fa-heart"></i>
                <%=t.likes.count%>
                <div class="top3-shop-method">
                <%= link_to "削除する", shop_path(t.id), method: :delete %>
                <%= link_to "詳しく見る", shop_path(t.id) %>
                </div>    
            </div>
　　        <%end%>
            <% end %>
            <% end %>
        </div>
        </div>
    <% end %>
</div>
</div>


<div class="anm_mod right delay">
<div class="behind-box-3">
<div class="sections">
<div class="anm_mod right delay">
<div class="section-word-5">
<h3>お知らせ</h3>
</div>
</div>
</div>
<div class="anm_mod right delay">
<div class="info-container">
    <% @infos.each do |t| %>
        <div class="info">
        <p><%= t.body.truncate(15, omission: '...') %></p>
        <p><%= link_to "詳細へ", info_path(t.id) %></p>
        </div>
    <% end %>
</div>
</div>
</div>
</div>

<% if user_signed_in? && current_user.id == 1 %>

<%= link_to "投稿する", new_shop_path %>
<%= link_to "ジャンル投稿する", genres_path %>
<%= link_to "価格帯を投稿する", prices_path %>
<%= link_to "お知らせ投稿する", infos_path %>

<% end %>

<div class="page-top-box">
<div id="page_top">
<a href="#"></a>
</div>
<p>ページトップへ戻る</p>
</div>

<script src="https://embed.small.chat/T01DG63L5GSG01D1DTHFTR.js" async></script>

<div class="above-footer">
</div>

<script>
$(window).scroll(function() {
 　　// .animation 配下の　.anm_modを対象に見る
 $(".animation .anm_mod").each(function() {
  // スクロール中、各UIパーツ　.anm_modがブラウザ画面内に入ったら activeクラスが付与される
  const position = $(this).offset().top;
  const scroll = $(window).scrollTop();
  const windowHeight = $(window).height();
  if (scroll > position - windowHeight) {
   $(this).addClass("active");
  }
  // スクロール中、トップ画面付近まで戻ったら activeクラスを解除 ＝ 何度でもスクロールアニメが表現可能。一度しかアニメーションしたく無ければここを削除してください。
  if (scroll < 100) {
   $(this).removeClass("active");
  }
 });
});
</script>

<script>
$(function() {
    $('.a').slick({
        dots: true,
        autoplay: true,
        autoplaySpeed: 3000,
    });
});
</script>

<script>
var mySwiper = new Swiper ('.swiper-container', {
  loop: true,
  slidesPerView: 2,
  spaceBetween: 10,
  centeredSlides : true,
  pagination: '.swiper-pagination',
  nextButton: '.swiper-button-next',
  prevButton: '.swiper-button-prev'
})
</script>

<script>
$(function(){
    $("ul#menu li").hover(function(){
        $("> ul:not(:animated)" , this).animate({
            height : "toggle",
            opacity : "toggle"
        }, 500 );
    },
    function(){
        $("> ul" , this).fadeOut("slow");
    });
});
</script>