config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "shops/search" => "shops#search"

  get "shops/tagsearch" => "shops#tagsearch"

  get "shops/mapsearch" => "shops#mapsearch"

  get "shops/condition" => "shops#condisearch"

  get "shops/random" => "shops#randomsearch"

  get "shops/index2" => "shops#index2"

  get "shops/index3" => "shops#index3"

  get "shops/index4" => "shops#index4"

  get "shops/about" => "shops#about"

  get "top2" => "shops#top2"

  get "top" => "shops#top"

  resources :shops do
    resources :likes, only: [:create, :destroy]
  end

  resources :genres

  resources :infos

  resources :prices

  root 'shops#top'
end

app/models/price.rb
class Price < ApplicationRecord
    has_one :shop
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
    def index
        @prices = Price.all
    end
    def new
        @price = Price.new
    end
    def create
        @price = Price.new(price_params)
        if @price.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end
    def edit
        @price = Price.find(params[:id])
    end
    def update
        @price = Price.find(params[:id])
        if @price.update(price_params)
          redirect_to :action => "index", :id => @price.id
        else
          redirect_to :action => "new"
        end
    end
    def destroy
        Price.find(params[:id]).destroy
        redirect_to action: :index
    end

    private
    def price_params
        params.require(:price).permit(:pricerange)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/edit.html.erb
<h1>価格帯編集ページ</h1>

<%= form_for @price do |f| %>
    <div class="field">
        <p>ジャンル：<%= f.text_field :pricerange %></p>
        <%= f.submit "編集する" %>
    </div>
<% end %>

app/views/prices/index.html.erb
<h1>価格帯一覧</h1>

<% @prices.each do |t| %>
    <div class="price">
    <p>id：<%= t.id %>
    -><%= t.pricerange %>
    <%= link_to "編集する", edit_price_path(t.id) %>
    <%= link_to "削除する", price_path(t.id), method: :delete %>
    </p>
    </div>
<% end %>

<%= link_to "価格帯投稿", new_price_path %>
<%= link_to "トップページへ", top2_path %>

app/views/prices/new.html.erb
<h1>価格帯投稿ページ</h1>

<%= form_for @price do |f| %>
    <div class="field">
        <p>ジャンル：<%= f.text_field :pricerange %></p>
        <%= f.submit "投稿する" %>
    </div>
<% end %>